fetch("https://pokeapi.co/api/v2/pokemon-species/aegislash")
.then(response => response.json())
// .then(data => console.log(data))
.then(data => console.log(data.id))
.catch(error => console.error(error))